#@Description: Configure SSH passwordless among the master node (first host),
#   the master itself and the other nodes (rest of the hosts)
#@Parameters:
#   <ANSIBLE_INVENTORY>
#   <ANSIBLE_GROUP>
#   <LSGI_PATH>
#@Requirements:
#   Edit 'ansible_hosts' file with the remote hostnames before running this playbook
#@Authors: Janneth Rivera, Tere Gonzalez
#@Date: June 24 2016
#@How to run it: ansible-playbook sshCopy.yml -i <ANSIBLE_INVENTORY> --extra-vars "ANSIBLE_GROUP=$(ANSIBLE_GROUP) LSGI_PATH=$(LSGI_PATH)"
#   For example: ansible-playbook sshCopy.yml -i ./ansible_hosts --extra-vars "ANSIBLE_GROUP=lsgi_nodes LSGI_PATH=../.."

---
- hosts: "{{ANSIBLE_GROUP}}"
  vars:
    LSGI_HOME: "{{LSGI_PATH}}/LSGi"
    SSH_SCRIPT: "sshCopy.sh"

  tasks:

  - name: Setting permissions to SSH script...
    shell: "chmod 755 {{SSH_SCRIPT}}  chdir={{LSGI_HOME}}/config/"
    when: inventory_hostname == groups["{{ANSIBLE_GROUP}}"][0]

  - name: Setting ssh from first node to the rest
    shell: "./{{SSH_SCRIPT}}  chdir={{LSGI_HOME}}/config/"
    when: inventory_hostname == groups["{{ANSIBLE_GROUP}}"][0]
    register: ssh_status

  - debug: var=ssh_status


...

